runtime: python27
api_version: 1
service: default
threadsafe: true

handlers:
- url: /static
  static_dir: static
  application_readable: true
   
- url: /.*
  script: main.app
  
- url: /admin/.*
  script: admin.app
  login: admin